added a new normalize method: spike-in

diff --git a/bin/piSet_chipseq_for_Sam b/bin/piSet_chipseq_for_Sam
--- a/bin/piSet_chipseq_for_Sam
+++ b/bin/piSet_chipseq_for_Sam
@@ -27,6 +27,9 @@ help_info(){
 	echo0 1 "output:"
 	echo0 4 "\t-o <dir>\toutput directory. default: ./chipseq_pipeline"
 	echo0 4 "\t-p <string\toutput prefix name. if you want to set -p in multiple sample mode, plesae use like -p \"prefix1 prefix2 prefix3\" and keep coordinate with sample_prefix_name in sample information file. default: sample name"
+	echo0 1 "spike-ins:"
+	echo0 4 "\t-S <index>\tbowtie2 index for spike-ins; please use bowtie2-build to build it."
+	echo0 4 "\t-s <concentration>\tconcentration of spikein used in the lirabry. Set this parameter if you want to normalize signals to spike-ins instead of depth."
 	echo0 6 "other optional:"
 	echo0 6 "\t-q qvalue used for macs2 peak calling"
 	echo0 6 "\t-i <index>\tbowtie2 index for genome mapping. default: genome/Bowtie2Index/genome"
@@ -35,7 +38,7 @@ help_info(){
 	echo0 6 "\t-k <file>\ttransposon.size file if needed. default: genome/genome.transposon.size"
 	echo0 6 "\t-c <int>\tCPU number used. default: 1"
 	echo0 5 "\tsuggestion for running CUTRUN data:"
-	echo0 5 "\tpiSet_chipseq -l "in.1.fq.gz in.negative.1.fq.gz" -I -g genome -o outputdir -q 0.001 -c cpu"
+	echo0 5 "\tpiSet_chipseq -l 'in.1.fq.gz in.negative.1.fq.gz' -I -g genome -o outputdir -q 0.001 -c cpu"
 }
 
 if [ $# -lt 1 ];then
@@ -50,7 +53,7 @@ MAX_FRAGMENT=700
 MAP_ENGINE=bowtie2
 QVALUE=0.05
 
-while getopts "hl:r:g:i:C:ao:p:c:X:PTRM:q:It:Tk:" OPTION; do
+while getopts "hl:r:g:i:C:ao:p:c:X:PTRM:q:It:Tk:S:s" OPTION; do
 	case $OPTION in
 		h)	help_info && exit 1;;
 		l)	LEFT=(${OPTARG});;
@@ -71,6 +74,8 @@ while getopts "hl:r:g:i:C:ao:p:c:X:PTRM:q:It:Tk:" OPTION; do
 		I)	IF_INPUT=1;;
 		t)	INDEX_TE=${OPTARG};;
 		k)	TRANSPOSON_SIZE=${OPTARG};;
+		S)	INDEX_SPIKEIN=${OPTARG};;
+		s)	IF_NOR_SPIKEIN=1;;
 		*)	help_info && exit 1
 	esac
 done
@@ -207,6 +212,35 @@ do
 		THIS_LEFT=${TEMP_LEFT}
 		THIS_RIGHT=${RIGHT[${SAMPLE_INDEX}]}
 	fi
+	# mapping to spikeins via bowtie2 and sort the bam files into bed files
+	if [ ! -z ${INDEX_SPIKEIN} ];then
+		echo0 2 "map to spike-ins and process reads"
+		if [ -z ${RIGHT[${SAMPLE_INDEX}]} ];then # single-end
+			bowtie2 -p ${CPU} --very-sensitive --no-unal -x ${INDEX_SPIKEIN} -U ${THIS_LEFT} -S ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sam > ${OUTDIR}/log/${PREFIX[${SAMPLE_INDEX}]}.bowtie2.spikein.log 2>&1 || (echo0 0 "bowtie2 error, please check ${OUTDIR}/log/${PREFIX[${SAMPLE_INDEX}]}.bowtie2.spikein.log" && exit 1)
+		else # paired-end
+			bowtie2 -p ${CPU} --very-sensitive --no-unal --no-mixed --no-discordant -I 10 -X ${MAX_FRAGMENT} -x ${INDEX_SPIKEIN} -1 ${THIS_LEFT} -2 ${THIS_RIGHT} -S ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sam > ${OUTDIR}/log/${PREFIX[${SAMPLE_INDEX}]}.bowtie2.spikein.log 2>&1 || (echo0 0 "bowtie2 error, please check ${OUTDIR}/log/${PREFIX[${SAMPLE_INDEX}]}.bowtie2.spikein.log" && exit 1)
+		fi
+		samtools view -@ ${CPU} -bhS -o ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.bam ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sam || (echo0 0 "samtools view error" && exit 1)
+		if [ -z ${RIGHT[${SAMPLE_INDEX}]} ];then
+			samtools sort -@ ${CPU} -o ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sort.bam ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.bam || (echo0 0 "samtools sort error" && exit 1)
+		else
+			samtools sort -n -@ ${CPU} -o ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sortByName.bam ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.bam || (echo0 0 "samtools sort error" && exit 1)
+		fi
+		if [ -z ${RIGHT[${SAMPLE_INDEX}]} ];then
+			BAM_SPIKEIN=${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sort.bam 
+		else
+			samtools sort -@ ${CPU} -o ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sort.bam ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sortByName.bam
+			BAM_SPIKEIN=${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sortByName.bam 
+		fi
+		samtools index -@ ${CPU} ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.sort.bam || (echo0 0 "samtools index error" && exit 1) 
+		if [ -z ${RIGHT[${SAMPLE_INDEX}]} ];then
+			bedtools bamtobed -i ${BAM_SPIKEIN} > ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.bed
+		else
+			bedtools bamtobed -bedpe -i ${BAM_SPIKEIN} | \
+				awk 'BEGIN{FS=OFS="\t"} {print $1,$2,$6,$7,$8,"+"}' | sort -k1,1 -k2,2n \
+				> ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.bed
+		fi
+	fi
 	# mapping via bowtie2|bwa mem|bwa aln
 	if [ "${MAP_ENGINE}" == "bowtie2" ];then # bowtie2 as engine
 		echo0 2 "mapping to genome via bowtie2......"
@@ -279,6 +313,9 @@ do
 	LIST_BAM+=(${BAM}) # add final bam file name to LIST_BAM
 	samtools flagstat ${BAM} > ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.flagstat
 	FACTOR=`awk 'BEGIN{FS=" "} {if($0~/mapped \(/){print 1000000/$1}}' ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.flagstat`
+	if [ ! -z ${IF_NOR_SPIKEIN} ];then
+		FACTOR=`awk -v c=${IF_NOR_SPIKEIN} '{s++} END{print s/c}' ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.spikein.bed`
+	fi
 	echo0 3 "factor used for normalization: ${FACTOR}"
 	echo -e "${FACTOR}" > ${OUTDIR}/bowtie2/${PREFIX[${SAMPLE_INDEX}]}.factor
 	# bam to bed and then to bigWig
diff --git a/bin/piSet_install_genome b/bin/piSet_install_genome
--- a/bin/piSet_install_genome
+++ b/bin/piSet_install_genome
@@ -227,7 +227,7 @@ fi
 # download gtf/gff annotation file from Ensemble/Refseq
 if [ ! -f ${GENOME}.gtf ];then
 	T_SPECIES=`awk -v a="${SPECIES}" 'BEGIN{print tolower(substr(a,1,1))substr(a,2,length(a)-1)}'`
-	echo0 2 "try download ${GENOME}.gtf from current ensembl release first......" && wget -nd -q ftp://ftp.ensembl.org/pub/current_gtf/${T_SPECIES/ /_}/*[0-9].gtf.gz && zcat *.gtf.gz | awk 'BEGIN{FS=OFS="\t"} {if($1!~/^#/){$1="chr"$1;if($9!~/gene_name/){split($9,a,"gene_id \"");split(a[2],b,"\";");$9=$9" gene_name \""b[1]"\";"}};print $0}' > t && mv t ${GENOME}.gtf && touch .have_ensembl_gtf || (echo0 0 "genome annotation download from current ensembl release failed, please check network connection or accessibility to ftp://ftp.ensembl.org/pub/current_gtf/${T_SPECIES/ /_}. Change to Refseq for genome annotation file download ......")
+	echo0 2 "try download ${GENOME}.gtf from current ensembl release first......" && wget -nd -q ftp://ftp.ensembl.org/pub/current_gtf/${T_SPECIES// /_}/*[0-9].gtf.gz && zcat *.gtf.gz | awk 'BEGIN{FS=OFS="\t"} {if($1!~/^#/){$1="chr"$1;if($9!~/gene_name/){split($9,a,"gene_id \"");split(a[2],b,"\";");$9=$9" gene_name \""b[1]"\";"}};print $0}' > t && mv t ${GENOME}.gtf && touch .have_ensembl_gtf || (echo0 0 "genome annotation download from current ensembl release failed, please check network connection or accessibility to ftp://ftp.ensembl.org/pub/current_gtf/${T_SPECIES/ /_}. Change to Refseq for genome annotation file download ......")
 fi
 
 if [ -f .have_ensembl_gtf ];then
@@ -375,7 +375,7 @@ if [ -z ${IF_TRN} ];then
 	if [ ! -f ${GENOME}.fa.out ];then
 		(rsync -a -P rsync://hgdownload.cse.ucsc.edu/goldenPath/${GENOME}/database/*rmsk.txt.gz ./ && zcat *rmsk.txt.gz > ${GENOME}.fa.out && touch .have_ucsc_rmsk) || ("rmsk download failed, please check network connection or accessibility to http://hgdownload.cse.ucsc.edu/goldenPath/${GENOME}/database/, change to Refseq to download rmsk annotation")
 		if [ -f .have_ucsc_rmsk ];then
-			echo0 2 "make rmsk bed just for LINE, SINE, LTR, DNA elements......" && awk 'BEGIN{FS=" ";OFS="\t"} {if(NR>3 && $12~/DNA|SINE|LINE|LTR/){if($10=="+"){strand="+";st=$14;ed=$15}else{strand="-";st=$16;ed=$15};print $6,$7-1,$8,$11,$3/10,strand,$12,$13,st,ed}}' ${GENOME}.fa.out > ${GENOME}.rmsk.bed9
+			echo0 2 "make rmsk bed just for LINE, SINE, LTR, DNA elements......" && awk 'BEGIN{FS=" ";OFS="\t"} {if(NR>3 && $12~/DNA|SINE|LINE|LTR/){if($10=="+"){strand="+";st=$14;ed=$15}else{strand="-";st=$16;ed=$15};print $6,$7,$8,$11,$3/10,strand,$12,$13,st,ed}}' ${GENOME}.fa.out > ${GENOME}.rmsk.bed9
 			sed -i 's/_I-int/_I/' ${GENOME}.rmsk.bed9 # keep identical with repbase name
 		else
 			echo0 2 "download repeatMasker output from Refseq......"
@@ -390,7 +390,7 @@ fi
 # make rmsk annotation bed file
 if [ ! -f ${GENOME}.rmsk.bed9 ];then
 	if [ -f ${GENOME}.fa.out ] && [ -z ${IF_TRN} ];then
-		echo0 2 "make rmsk bed just for LINE, SINE, LTR, DNA elements......" && awk 'BEGIN{FS=" ";OFS="\t"} {if(NR>3 && $11~/DNA|SINE|LINE|LTR/){if($9=="+"){strand="+";st=$12}else{strand="-";st=$14};split($11,family,"/");print $5,$6-1,$7,$10,$2,strand,family[1],family[2],st}}' ${GENOME}.fa.out > ${GENOME}.rmsk.bed9
+		echo0 2 "make rmsk bed just for LINE, SINE, LTR, DNA elements......" && awk 'BEGIN{FS=" ";OFS="\t"} {if(NR>3 && $11~/DNA|SINE|LINE|LTR/){if($9=="+"){strand="+";st=$12}else{strand="-";st=$14};split($11,family,"/");print $5,$6,$7,$10,$2,strand,family[1],family[2],st}}' ${GENOME}.fa.out > ${GENOME}.rmsk.bed9
 		if [ -z ${RMSK_URL} ];then
 			[ ! -f *_assembly_report.txt ] && wget -nd -q ${REFSEQ_URL}/*_assembly_report.txt
 			[ ! -f *_assembly_report.txt ] && echo0 0 "assembly report download failed, please check network connection or accessibility to ${REFSEQ_URL}" && exit 1
@@ -411,6 +411,7 @@ if [ ! -f ${GENOME}.transposon.fa ];then
 	merge_repbase_LTR.py ${GENOME}.transposon.original.fa ${GENOME}.t # merge LTR and I for LTR elements.
 	merge_repbase_LINE1.py ${GENOME}.t ${GENOME}.transposon.fa # merge 5end, 3end and orf2 for LINE elements.
 	rm ${GENOME}.t
+	[ ! -f ${GENOME}.transposon.fa ] && cp ${GENOME}.transposon.original.fa ${GENOME}.transposon.fa 
 fi
 
 # rename LTR and I for rmsk genomic copies
